[package]
name = "chia-puzzles"
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = ["proc-macro"]

[dependencies]
chia-puzzles-macro = { version = "0.1.0", path = "./proc-macro" }
